"""email nullable for phone-only signup

Revision ID: 84613258788f
Revises: 661b294a43f5
Create Date: 2026-09-22 09:25:21.393790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '84613258788f'
down_revision: Union[str, None] = '661b294a43f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
